package view.open;

public enum			ButtonId
{
	// Info
	INFO_OK,

	// Question
	QUESTION_ANSWER_A,
	QUESTION_ANSWER_B,

	// Hero selector
	HERO_SELECTOR_CREATE_0,
	HERO_SELECTOR_CREATE_1,
	HERO_SELECTOR_CREATE_2,
	HERO_SELECTOR_CREATE_3,
	HERO_SELECTOR_SELECT_0,
	HERO_SELECTOR_SELECT_1,
	HERO_SELECTOR_SELECT_2,
	HERO_SELECTOR_SELECT_3,
	HERO_SELECTOR_DELETE_0,
	HERO_SELECTOR_DELETE_1,
	HERO_SELECTOR_DELETE_2,
	HERO_SELECTOR_DELETE_3,
	HERO_SELECTOR_INFO_0,
	HERO_SELECTOR_INFO_1,
	HERO_SELECTOR_INFO_2,
	HERO_SELECTOR_INFO_3,

	// Hero info
	HERO_INFO_OK,

	// Name entry
	NAME_ENTRY_ENTER,

	// Class selector
	CLASS_SELECTOR_SELECT_0,
	CLASS_SELECTOR_SELECT_1,
	CLASS_SELECTOR_SELECT_2,
	CLASS_SELECTOR_SELECT_3,

	// Map
	MAP_ARROW_UP,
	MAP_ARROW_LEFT,
	MAP_ARROW_RIGHT,
	MAP_ARROW_DOWN,
	MAP_HERO_STATS,
	MAP_HERO_INVENTORY,

	// Hero stats
	HERO_STATS_OK,

	// Hero inventory
	HERO_INVENTORY_OK,

	// Battle
	BATTLE_PROCEED;

	public ButtonId	applyOffset(int offset)
	{
		return values()[this.ordinal() + offset];
	}
}
